# Generated by Django 5.0.3 on 2024-03-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='попытка')),
                ('attempt_time', models.DateTimeField(auto_now_add=True, verbose_name='время попытки')),
                ('attempt_result', models.CharField(default='успешно', max_length=150, verbose_name='результат попытки')),
            ],
            options={
                'verbose_name': 'попытка',
                'verbose_name_plural': 'попытки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='рассылка')),
                ('recipients', models.CharField(max_length=150, verbose_name='Получатели')),
                ('message', models.TextField(blank=True, null=True, verbose_name='сообщение')),
                ('start_time', models.DateTimeField(verbose_name='старт рассылки')),
                ('stop_time', models.DateTimeField(verbose_name='окончание рассылки')),
                ('next_sending', models.DateTimeField(verbose_name='следующая отправка')),
                ('frequency', models.CharField(max_length=50, verbose_name='периодичность рассылки')),
                ('status', models.CharField(default='создана', max_length=150, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
