# Generated by Django 5.0.3 on 2024-03-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('jobs', '0002_alter_mailing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='recipients',
        ),
        migrations.AddField(
            model_name='mailing',
            name='recipients',
            field=models.ManyToManyField(to='clients.client', verbose_name='Получатели'),
        ),
    ]
