# Generated by Django 5.0.3 on 2024-03-28 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_mailing_recipients_mailing_recipients'),
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mess.message', verbose_name='сообщение'),
        ),
    ]
