# Generated by Django 5.0.3 on 2024-03-29 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_mailing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='attempt_mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.mailing', verbose_name='название рассылки'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='ответ сервера'),
        ),
    ]
