# Generated by Django 5.0.3 on 2024-04-22 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_attempt_attempt_mailing_attempt_server_response"),
        ("mess", "0003_alter_message_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="mess.message", verbose_name="сообщение"
            ),
        ),
    ]
