# Generated by Django 5.0.3 on 2024-03-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_alter_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(default=0, verbose_name='текст сообщения'),
        ),
    ]
