# Generated by Django 5.0.3 on 2024-05-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("body", models.TextField(verbose_name="Содержимое")),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/", verbose_name="Изображение")),
                ("views_count", models.IntegerField(default=0, verbose_name="просмотры")),
                ("create_date", models.DateField(auto_now_add=True, verbose_name="Дата публикации")),
            ],
            options={
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
